				  {include file='main_header.tpl'}
 
  <tr>
    <td colspan="5" valign="top"><table align="center" border="0" cellpadding="0" cellspacing="0" width="732">
      <tbody><tr>
        <td width="10%"><img src="{$tempdir}/img/faq.png" alt="" width="128" height="128"></td>
        <td valign="top" width="90%"><p class="whitetxt1"><span class="price"><br><br><br>FAQ</span>
        </p>		</td>
      </tr>
      <tr>
        <td colspan="2" class="linebg1">&nbsp;</td>
      </tr>
      <tr>
        <td colspan="2" class=""><table align="center" border="0" cellpadding="0" cellspacing="0" width="742">
          <tbody><tr>
            <td class="acbdytop"></td>
          </tr>
          <tr>
            <td bgcolor="#2695a1"><ol type="1">
			<li class="faq" type="1"><strong> What is involved in creating  a website?</strong></li>
			<p>Creating a website, typically, involves analysis of requirements, planning, web design and development. After an in-depth analysis of our client’s requirements, a technical and aesthetic feed is generated by us that is passed on to the team of web design and developers.</p>
			<p class="dot"></p>
			<li class="faq" type="1"><strong> What is involved in creating  a website?</strong></li>
			<p>Creating a website, typically, involves analysis of requirements, planning, web design and development. After an in-depth analysis of our client’s requirements, a technical and aesthetic feed is generated by us that is passed on to the team of web design and developers.</p>
			<p class="dot"></p>
			</ol></td>
          </tr>
          <tr>
            <td class="acbdybtm"></td>
          </tr>
          <tr>
            <td>&nbsp;</td>
          </tr>
  				  {include file='main_footer.tpl'}