<?php 
### Copyright (c) 2004, The dotProject Development Team dotproject.net and sf.net/projects/dotproject ###
### All rights reserved. Released under BSD License. For further Information see ./includes/config-dist.php ###

### CONFIGURATION FILE AUTOMATICALLY GENERATED BY THE DOTPROJECT INSTALLER ###
### FOR INFORMATION ON MANUAL CONFIGURATION AND FOR DOCUMENTATION SEE ./includes/config-dist.php ###

$dPconfig['dbtype'] = "mysql";
$dPconfig['dbhost'] = "localhost";
$dPconfig['dbname'] = "etel_dotproject";
$dPconfig['dbuser'] = "etel_dp";
$dPconfig['dbpass'] = "dpdpdp";
$dPconfig['dbpersist'] = false;
$dPconfig['root_dir'] = $baseDir;
$dPconfig['base_url'] = $baseUrl;
?>